/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author interim_misc
 */


import javax.swing.*;

public class frame2 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 189));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tax Calculator");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jButton1.setText("click here to start calculating your tax");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(484, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
               // TODO add your handling code here:
        
        String salary = JOptionPane.showInputDialog(new JFrame(), "What is your gross annual salary?");  // ask for the user's salary
        double calsalary = Double.parseDouble(salary); // make the string they input into a double
        
        if (calsalary >= 10000) { // if their salary is > or = to 10,000...
            double tax = 0.2 * calsalary; //calculate 0.2 tax of their salary.
            double netsalary = calsalary - tax;
            JOptionPane.showMessageDialog(new JFrame(), "Your gross annual salary was "+salary+". Your calculated tax is "+tax+". Your net salary is "+netsalary+"." ); // read the statement
        }
        else if (calsalary >= 8000) {
            double tax = 0.15 * calsalary; // the variable tax = calculated 0.15 tax of their salary.
            double netsalary = calsalary - tax; // the variable net salary = the input salary - tax
            JOptionPane.showMessageDialog(new JFrame(), "Your gross annual salary was "+salary+". Your calculated tax is "+tax+". Your net salary is "+netsalary+"." ); // read the statement
        } 
        else if (calsalary >= 7000) {
             double tax = 0.12 * calsalary; // the variable tax = calculated 0.12 tax of their salary.
             double netsalary = calsalary - tax; // the variable net salary = the input salary - tax
            JOptionPane.showMessageDialog(new JFrame(), "Your gross annual salary was "+salary+". Your calculated tax is "+tax+". Your net salary is "+netsalary+"." ); // read the statement
        } 
        else if (calsalary >= 5000) {
            double tax = 0.09 * calsalary;  // the variable tax = calculated 0.09 tax of their salary.
            double netsalary = calsalary - tax; // the variable net salary = the input salary - tax
            JOptionPane.showMessageDialog(new JFrame(), "Your gross annual salary was "+salary+". Your calculated tax is "+tax+". Your net salary is "+netsalary+"." ); // read the statement
        } 
        else if (calsalary >= 3000) {
            double tax = 0.07 * calsalary; // the variable tax = calculated 0.07 tax of their salary.
            double netsalary = calsalary - tax; // the variable net salary = the input salary - tax
            JOptionPane.showMessageDialog(new JFrame(), "Your gross annual salary was "+salary+". Your calculated tax is "+tax+". Your net salary is "+netsalary+"." ); // read the statement
        } 
        else {
            double tax = 0.05 * calsalary;// the variable tax = calculated 0.05 tax of their salary.
            double netsalary = calsalary - tax; // the variable net salary = the input salary - tax
            JOptionPane.showMessageDialog(new JFrame(), "Your gross annual salary was "+salary+". Your calculated tax is "+tax+". Your net salary is "+netsalary+"." ); // read the statement
        }            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
